language: c
sudo: false

notifications:
  email:
    recipients:
      - adam.stevens@uwa.edu.au
    on_success: change
    on_failure: always

env:
  global:
    - NUMPY_VERSION=1.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - libgsl0-dev

matrix:
  fast_finish: true

  include:
    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER=clang FAMILY=clang V='Apple LLVM 7.0.0' PYTHON_VERSION=3.5
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION matplotlib
        - source activate test
        - conda install -q --yes -c asmeurer gsl

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: COMPILER=clang FAMILY=clang V='Apple LLVM 7.0.0' PYTHON_VERSION=3.5
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION matplotlib
        - source activate test
        - conda install -q --yes -c asmeurer gsl


    - os: linux
      dist: trusty
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=2.7
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION matplotlib
        - source activate test


install:
  - make CC=$COMPILER

script:
  - python test.py


